version: "2"
run:
  issues-exit-code: 1
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
